# Generated by Django 2.1.7 on 2019-03-05 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('cache_seconds', models.IntegerField()),
                ('threshold', models.FloatField()),
                ('google_id', models.CharField(max_length=20)),
                ('delta', models.FloatField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('description', models.TextField()),
                ('scots', models.TextField()),
                ('terrible', models.BooleanField()),
                ('nighttime', models.BooleanField(default=False)),
                ('delta', models.FloatField(default=0)),
                ('colder', models.FloatField(default=-273.15)),
                ('cold', models.FloatField(default=5)),
                ('fair', models.FloatField(default=13)),
                ('warm', models.FloatField(default=16)),
                ('clothing_cold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cold', to='www.ClothingIcon')),
                ('clothing_colder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colder', to='www.ClothingIcon')),
                ('clothing_fair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fair', to='www.ClothingIcon')),
                ('clothing_warm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warm', to='www.ClothingIcon')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='weather',
            name='weather_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_day', to='www.WeatherIcon'),
        ),
        migrations.AddField(
            model_name='weather',
            name='weather_night',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_night', to='www.WeatherIcon'),
        ),
    ]
