# Generated by Django 2.1.7 on 2021-05-07 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='nighttime',
        ),
    ]
