# Generated by Django 2.0.2 on 2018-04-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='night',
            field=models.BooleanField(default=False),
        ),
    ]
