# Generated by Django 5.2.14 on 2026-05-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_remove_weather_nighttime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'Settings'},
        ),
    ]
