# Generated by Django 2.0.2 on 2018-04-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_weather_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='google_id',
            field=models.CharField(default='UA-41104029-1', max_length=20),
        ),
        migrations.AlterField(
            model_name='settings',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
