# Generated by Django 2.0.2 on 2018-04-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_auto_20180409_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='delta',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='weather',
            name='delta',
            field=models.FloatField(default=0),
        ),
    ]
