# Generated by Django 2.0.2 on 2018-04-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_auto_20180409_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='google_id',
            field=models.CharField(max_length=20),
        ),
    ]
