# Generated by Django 2.0.2 on 2018-04-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_auto_20180409_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='cold',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='settings',
            name='colder',
            field=models.FloatField(default=-273.15),
        ),
        migrations.AddField(
            model_name='settings',
            name='fair',
            field=models.FloatField(default=12.0),
        ),
        migrations.AddField(
            model_name='settings',
            name='warm',
            field=models.FloatField(default=16.0),
        ),
    ]
