# Generated by Django 2.0.2 on 2018-04-10 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0005_auto_20180410_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='cold',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='colder',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='fair',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='warm',
        ),
    ]
