# Generated by Django 2.0.2 on 2018-04-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0006_auto_20180410_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='delta',
            field=models.FloatField(default=5),
        ),
    ]
