# Generated by Django 2.0.2 on 2018-04-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0007_settings_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='delta',
            field=models.FloatField(default=0),
        ),
    ]
