# Generated by Django 2.0.2 on 2018-04-18 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0008_weather_delta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='weather',
            name='cold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cold', to='www.Clothing'),
        ),
        migrations.AddField(
            model_name='weather',
            name='colder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colder', to='www.Clothing'),
        ),
        migrations.AddField(
            model_name='weather',
            name='fair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fair', to='www.Clothing'),
        ),
        migrations.AddField(
            model_name='weather',
            name='warm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warm', to='www.Clothing'),
        ),
    ]
