# Generated by Django 2.0.2 on 2018-04-18 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0008_auto_20180418_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='weather_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_icon', to='www.WeatherIcon'),
        ),
    ]
