# Generated by Django 2.0.2 on 2018-04-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0009_auto_20180418_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='cold',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='settings',
            name='colder',
            field=models.FloatField(default=-273.15),
        ),
        migrations.AddField(
            model_name='settings',
            name='fair',
            field=models.FloatField(default=13),
        ),
        migrations.AddField(
            model_name='settings',
            name='warm',
            field=models.FloatField(default=16),
        ),
    ]
