# Generated by Django 2.0.2 on 2018-04-18 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0010_auto_20180418_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='night',
            new_name='nighttime',
        ),
    ]
