# Generated by Django 2.0.2 on 2018-04-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('www', '0011_auto_20180418_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Clothing',
            new_name='ClothingIcon',
        ),
    ]
