# Generated by Django 2.0.2 on 2018-04-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0012_auto_20180418_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='cold',
            new_name='clothing_cold',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='colder',
            new_name='clothing_colder',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='fair',
            new_name='clothing_fair',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='warm',
            new_name='clothing_warm',
        ),
    ]
