# Generated by Django 2.1.2 on 2019-03-05 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0016_auto_20180418_2112'),
        ('www', '0011_auto_20180418_2115'),
    ]

    operations = [
    ]
